#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Thrift::API::HiveClient2::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant PRIMITIVE_TYPES => [
0 => 1,
1 => 1,
2 => 1,
3 => 1,
4 => 1,
5 => 1,
6 => 1,
7 => 1,
8 => 1,
9 => 1,
];

use constant COMPLEX_TYPES => [
10 => 1,
11 => 1,
12 => 1,
13 => 1,
14 => 1,
];

use constant COLLECTION_TYPES => [
10 => 1,
11 => 1,
];

use constant TYPE_NAMES => {
0 => "BOOLEAN",
1 => "TINYINT",
2 => "SMALLINT",
3 => "INT",
4 => "BIGINT",
5 => "FLOAT",
6 => "DOUBLE",
7 => "STRING",
8 => "TIMESTAMP",
9 => "BINARY",
10 => "ARRAY",
11 => "MAP",
12 => "STRUCT",
13 => "UNIONTYPE",
};

1;
